### ISSUE TITLE
Use SID for administrators group

### ISSUE THREAD

**Issue by Rockavina** [jseerden/SLAPS#1]
Non-English Windows renames "Administrators" group, so SID should be used instead.

New-LocalAdmin.ps1
Add-LocalGroupMember -SID 'S-1-5-32-544' -Member $userName

**Comment by markuslosco** [comment]
@Rockavina Rockavina yes good idea, i use the same solution. And if you wish to use the local Administrator useraccount you need to activate him: 
        if ((Get-LocalUser -Name $userName).Enabled)
           {
           Enable-LocalUser -Name $userName
           }

**Comment by jseerden** [comment]
@Rockavina thanks for contributing! This issue has been resolved in #2
