### ISSUE TITLE
Minor differences between this and TechNet Gallery

### ISSUE THREAD

**Issue by webash** [jseerden/SLAPS#3]
There are (somewhat) minor differences between the script here and the on TechNet Gallery. Which one is newer, and which one do you recommend using?

**Comment by jseerden** [comment]
Hi @webash , this GitHub version is the latest and recommended version.

**Comment by webash** [comment]
Your blog posts currently link to the TechNet gallery; so hence my confusion :)

**Comment by webash** [comment]
...while I'm here - thanks massively for this basis. We've adopted it. I've made some changes to make the scripts a bit more resilient to failure which I can share back in case you're interested. Additionally it looks like the latest version of an Azure Function uses PS Core 6.1.2, which has some fundamental differences, which I've factored in. Watch out for a PR in the next few weeks.

**Comment by jseerden** [comment]
Thanks and looking forward to it!
