### ISSUE TITLE
Response status code does not indicate success: 405 (Method Not Allowed).Exception 

### ISSUE THREAD

**Issue by hansdampf01** [jseerden/SLAPS#6]
Hello,

Im getting alot of errors when Testing the function and create the Test Key.
Its not able to parse the key into keyvault for some reason.
The key will be created and shown in the end.

Errors shown like.

Error] ERROR: Response status code does not indicate success: 405 (Method Not Allowed).Exception             :Type       : Microsoft.PowerShell.Commands.HttpResponseExceptionResponse   : StatusCode: 405, ReasonPhrase: 'Method Not Allowed', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:{Cache-Control: no-cachePragma: no-cachex-ms-keyvault-region: westeuropex-ms-request-id: a98c4a94-d199-4df9-b708-577cb3d94a5dx-ms-keyvault-service-version: 1.1.60.0x-ms-keyvault-network-info: conn_type=Ipv4;addr=52.166.217.1;act_addr_fam=InterNetwork;X-AspNet-Version: 4.0.30319X-Powered-By: ASP.NETStrict-Transport-Security: max-age=31536000;includeSubDomainsX-Content-Type-Options: nosniffDate: Thu, 24 Sep 2020 19:38:04 GMTContent-Length: 70Content-Type: application/json; charset=utf-8Expires: -1}TargetSite :Name          : ThrowTerminatingErrorDeclaringType : System.Management.Automation.MshCommandRuntime, System.Management.Automation, Version=7.0.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35MemberType    : MethodModule        : System.Management.Automation.dllStackTrace :at System.Management.Automation.MshCommandRuntime.ThrowTerminatingError(ErrorRecord errorRecord)Message    : Response status code does not indicate success: 405 (Method Not Allowed).Source     : System.Management.AutomationHResult    : -2146233088TargetObject          : Method: PUT, RequestUri: 'https://RemovedKeyVaultName.vault.azure.net/secrets//?api-version=7.0', Version: 1.1, Content: System.Net.Http.ByteArrayContent, Headers:{Authorization: Bearer

Would you mind helping me on this?

**Comment by hansdampf01** [comment]
You actually mentioned to make sure about the " when copying from your site... I thought it was in regards of the Script not the Test input. Solved now- no more errors.

**Comment by jseerden** [comment]
Thanks for updating the status. Glad to hear it is resolved for you!
